       
       Thermochemistry v.1.0.0 (28.05.2024)
       Copyright: Yury Minenkov
       N.N. Semenov Federal Research Center
       of Chemical Physics RAS
       119991 Moscow, The Russian Federation
       Kosygina street, 4
       
The thermochemical analysis of the Molecule:                 O2N1C6H5

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  O     8   15.99491      -2.3053390000      -1.1804530000       0.1129300000
  O     8   15.99491      -2.4223350000       1.0265750000      -0.2128080000
  N     7   14.00307       1.7775770000      -1.1901450000       0.1705250000
  C     6   12.00000      -0.2811650000       0.0123400000      -0.0343410000
  C     6   12.00000       0.4075720000       1.2074290000      -0.2002880000
  C     6   12.00000       0.4518620000      -1.1573010000       0.1474500000
  C     6   12.00000       1.7876600000       1.1820390000      -0.1775450000
  C     6   12.00000       2.4216980000      -0.0390890000       0.0104320000
  C     6   12.00000      -1.7597080000       0.0343040000      -0.0579180000
  H     1    1.00782      -0.1515880000       2.1243930000      -0.3425720000
  H     1    1.00782      -0.0611380000      -2.1037890000       0.2793380000
  H     1    1.00782       2.3687140000       2.0871480000      -0.3023800000
  H     1    1.00782       3.5065850000      -0.0934960000       0.0333520000
  H     1    1.00782      -3.2636480000      -1.0555120000       0.0813420000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.98300
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.09732811     -0.02669259     -0.02608320

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       126.51511        -4.82292        -4.83030
    y        -4.82292       404.74996        18.10751
    z        -4.83030        18.10751       525.81516

              Principal moments of inertia (amu*A**2): 
             126.38033000         528.54012000         402.15979000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              395932.42034       The ln(Q)   12.88900

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       28.59391  (cal/mol*K)    119.63693    (J/mol*K)         0.00004557  (hartree/K)
  G rotation       -7.63655   (kcal/mol)    -31.95131     (kJ/mol)        -0.01216960    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   123.03203   amu

              *****      Translation thermodynamic functions     ******

  Q translation            53639227.92083       The ln(Q)   17.79779
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       40.33590  (cal/mol*K)    168.76543    (J/mol*K)         0.00006428  (hartree/K)
  G translation      -10.54494   (kcal/mol)    -44.12001     (kJ/mol)        -0.01680441    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                            The approximation : msRRHO of Grimme
                        TAU= 25.0 ALPHA=  4.0 ENTHALPY_CORRECTION=    1
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       64.140          63.050         yes       3.81201    0.090        0.590        4.334       -0.702        1.948
  2      159.000         156.297         yes       1.88811    0.223        0.620        2.594       -0.153        1.895
  3      210.260         206.686         yes       1.58438    0.295        0.641        2.073        0.023        1.830
  4      388.610         382.004         yes       1.18804    0.546        0.751        1.031        0.444        1.509
  5      389.430         382.810         yes       1.18717    0.547        0.752        1.028        0.446        1.507
  6      430.120         422.808         yes       1.14941    0.604        0.785        0.882        0.522        1.421
  7      497.670         489.210         yes       1.10418    0.699        0.845        0.686        0.641        1.274
  8      599.770         589.574         yes       1.06172    0.843        0.947        0.468        0.807        1.054
  9      625.260         614.631         yes       1.05431    0.879        0.974        0.425        0.847        1.001
 10      661.930         650.677         yes       1.04524    0.930        1.014        0.370        0.904        0.927
 11      727.850         715.477         yes       1.03270    1.023        1.090        0.288        1.004        0.800
 12      769.440         756.360         yes       1.02669    1.081        1.139        0.246        1.066        0.725
 13      800.480         786.872         yes       1.02295    1.125        1.177        0.218        1.111        0.673
 14      859.230         844.623         yes       1.01727    1.207        1.249        0.174        1.197        0.580
 15      973.460         956.911         yes       1.00997    1.368        1.395        0.111        1.362        0.427
 16     1009.360         992.201         yes       1.00840    1.418        1.442        0.097        1.413        0.386
 17     1025.890        1008.450         yes       1.00776    1.442        1.464        0.090        1.437        0.368
 18     1046.360        1028.572         yes       1.00704    1.470        1.491        0.083        1.466        0.347
 19     1073.860        1055.604         yes       1.00617    1.509        1.528        0.075        1.505        0.320
 20     1134.930        1115.636         yes       1.00461    1.595        1.610        0.058        1.592        0.267
 21     1143.360        1123.923         yes       1.00443    1.607        1.621        0.057        1.604        0.260
 22     1214.140        1193.500         yes       1.00316    1.706        1.717        0.042        1.704        0.209
 23     1234.610        1213.622         yes       1.00287    1.735        1.745        0.039        1.733        0.196
 24     1330.210        1307.596         yes       1.00182    1.869        1.876        0.026        1.868        0.144
 25     1359.500        1336.389         yes       1.00158    1.910        1.917        0.023        1.910        0.131
 26     1402.420        1378.579         yes       1.00129    1.971        1.976        0.020        1.970        0.114
 27     1466.030        1441.107         yes       1.00096    2.060        2.064        0.015        2.060        0.092
 28     1525.370        1499.439         yes       1.00072    2.144        2.147        0.012        2.143        0.075
 29     1641.330        1613.427         yes       1.00042    2.307        2.308        0.007        2.306        0.050
 30     1664.410        1636.115         yes       1.00037    2.339        2.341        0.007        2.339        0.046
 31     1828.230        1797.150         yes       1.00017    2.569        2.570        0.003        2.569        0.026
 32     3172.680        3118.744         yes       1.00000    4.458        4.458        0.000        4.458        0.000
 33     3200.860        3146.445         yes       1.00000    4.498        4.498        0.000        4.498        0.000
 34     3211.190        3156.600         yes       1.00000    4.513        4.513        0.000        4.513        0.000
 35     3224.860        3170.037         yes       1.00000    4.532        4.532        0.000        4.532        0.000
 36     3793.870        3729.374         yes       1.00000    5.331        5.331        0.000        5.331        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  28.02343       The ln(Q)    3.33304
    H vibration       67.11751   (kcal/mol)    280.81968     (kJ/mol)         0.10695847    (hartree)
    U vibration       67.11751   (kcal/mol)    280.81968     (kJ/mol)         0.10695847    (hartree)
           ZPE        64.44581   (kcal/mol)    269.64126     (kJ/mol)         0.10270084    (hartree)
    S vibration       15.58450  (cal/mol*K)     65.20557    (J/mol*K)         0.00002484  (hartree/K)
   Cv vibration       20.60168  (cal/mol*K)     86.19744    (J/mol*K)         0.00003283  (hartree/K)
    G vibration       62.47099   (kcal/mol)    261.37863     (kJ/mol)         0.09955377    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total     595147762802279.50000       The ln(Q)   38.92862
        H total       69.48746   (kcal/mol)    290.73551     (kJ/mol)         0.11073521    (hartree)
        U total       68.89497   (kcal/mol)    288.25655     (kJ/mol)         0.10979102    (hartree)
       Cv total       26.56330  (cal/mol*K)    111.14086    (J/mol*K)         0.00004233  (hartree/K)
           ZPE        64.44581   (kcal/mol)    269.64126     (kJ/mol)         0.10270084    (hartree)
        S total       84.51432  (cal/mol*K)    353.60793    (J/mol*K)         0.00013468  (hartree/K)
        G total       44.88200   (kcal/mol)    187.78627     (kJ/mol)         0.07152395    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.10979102 (hartree)
                       Thermal correction to Enthalpy :   0.11073521 
              Thermal correction to Gibbs Free Energy :   0.07057976 (hartree)
              ZPE correction to the Electronic Energy :   0.10270084 (hartree)


