       
       Thermochemistry v.1.0.0 (28.05.2024)
       Copyright: Yury Minenkov
       N.N. Semenov Federal Research Center
       of Chemical Physics RAS
       119991 Moscow, The Russian Federation
       Kosygina street, 4
       
The thermochemical analysis of the Molecule:                 O2N1C6H5

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  O     8   15.99491      -2.3148270000      -1.1898800000       0.1137040000
  O     8   15.99491      -2.4321900000       1.0384930000      -0.2140710000
  N     7   14.00307       1.7838930000      -1.1968410000       0.1716560000
  C     6   12.00000      -0.2844410000       0.0125280000      -0.0343780000
  C     6   12.00000       0.4087240000       1.2121200000      -0.2010230000
  C     6   12.00000       0.4500690000      -1.1637040000       0.1484370000
  C     6   12.00000       1.7933130000       1.1855960000      -0.1780580000
  C     6   12.00000       2.4320220000      -0.0382670000       0.0104970000
  C     6   12.00000      -1.7661150000       0.0390070000      -0.0585730000
  H     1    1.00782      -0.1491770000       2.1326540000      -0.3439180000
  H     1    1.00782      -0.0625340000      -2.1139530000       0.2809760000
  H     1    1.00782       2.3740500000       2.0940860000      -0.3035290000
  H     1    1.00782       3.5201630000      -0.0918710000       0.0333800000
  H     1    1.00782      -3.2762070000      -1.0655230000       0.0824180000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     1.00000
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.09851221     -0.02642114     -0.02610264

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       128.06943        -4.64122        -4.89266
    y        -4.64122       407.86576        18.31905
    z        -4.89266        18.31905       530.42597

              Principal moments of inertia (amu*A**2): 
             127.94001000         533.18057000         405.24058000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              401642.65253       The ln(Q)   12.90332

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       28.62237  (cal/mol*K)    119.75599    (J/mol*K)         0.00004561  (hartree/K)
  G rotation       -7.64503   (kcal/mol)    -31.98681     (kJ/mol)        -0.01218312    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   123.03203   amu

              *****      Translation thermodynamic functions     ******

  Q translation            53639227.92083       The ln(Q)   17.79779
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       40.33590  (cal/mol*K)    168.76543    (J/mol*K)         0.00006428  (hartree/K)
  G translation      -10.54494   (kcal/mol)    -44.12001     (kJ/mol)        -0.01680441    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                            The approximation : msRRHO of Grimme
                        TAU= 25.0 ALPHA=  4.0 ENTHALPY_CORRECTION=    1
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       66.220          66.220         yes       3.65592    0.095        0.592        4.243       -0.673        1.951
  2      156.470         156.470         yes       1.88671    0.224        0.620        2.592       -0.153        1.895
  3      219.720         219.720         yes       1.52988    0.314        0.647        1.961        0.062        1.811
  4      379.250         379.250         yes       1.19103    0.542        0.749        1.042        0.439        1.514
  5      388.760         388.760         yes       1.18091    0.556        0.757        1.005        0.457        1.494
  6      422.790         422.790         yes       1.14942    0.604        0.785        0.883        0.522        1.421
  7      496.610         496.610         yes       1.10016    0.710        0.852        0.667        0.653        1.258
  8      602.130         602.130         yes       1.05788    0.861        0.960        0.446        0.827        1.027
  9      628.860         628.860         yes       1.05052    0.899        0.990        0.403        0.870        0.971
 10      661.680         661.680         yes       1.04280    0.946        1.027        0.355        0.921        0.904
 11      722.440         722.440         yes       1.03158    1.033        1.098        0.281        1.014        0.787
 12      751.540         751.540         yes       1.02733    1.074        1.133        0.251        1.058        0.734
 13      793.770         793.770         yes       1.02218    1.135        1.185        0.212        1.122        0.661
 14      847.010         847.010         yes       1.01707    1.211        1.252        0.172        1.201        0.576
 15      954.640         954.640         yes       1.01008    1.365        1.392        0.112        1.359        0.430
 16      992.040         992.040         yes       1.00841    1.418        1.442        0.097        1.413        0.386
 17     1010.560        1010.560         yes       1.00768    1.445        1.467        0.090        1.440        0.366
 18     1045.860        1045.860         yes       1.00647    1.495        1.514        0.078        1.491        0.330
 19     1058.970        1058.970         yes       1.00607    1.514        1.532        0.074        1.510        0.317
 20     1111.160        1111.160         yes       1.00471    1.588        1.603        0.060        1.586        0.271
 21     1133.160        1133.160         yes       1.00424    1.620        1.634        0.054        1.617        0.253
 22     1208.090        1208.090         yes       1.00295    1.727        1.737        0.040        1.725        0.200
 23     1228.980        1228.980         yes       1.00266    1.757        1.766        0.037        1.755        0.187
 24     1305.300        1305.300         yes       1.00184    1.866        1.873        0.027        1.865        0.145
 25     1358.220        1358.220         yes       1.00143    1.942        1.947        0.021        1.941        0.122
 26     1375.900        1375.900         yes       1.00131    1.967        1.972        0.020        1.966        0.115
 27     1449.170        1449.170         yes       1.00092    2.072        2.075        0.015        2.071        0.089
 28     1506.700        1506.700         yes       1.00070    2.154        2.157        0.011        2.154        0.073
 29     1603.860        1603.860         yes       1.00044    2.293        2.295        0.008        2.293        0.052
 30     1624.700        1624.700         yes       1.00039    2.323        2.324        0.007        2.322        0.048
 31     1783.090        1783.090         yes       1.00018    2.549        2.550        0.003        2.549        0.027
 32     3137.390        3137.390         yes       1.00000    4.485        4.485        0.000        4.485        0.000
 33     3165.520        3165.520         yes       1.00000    4.525        4.525        0.000        4.525        0.000
 34     3180.940        3180.940         yes       1.00000    4.547        4.547        0.000        4.547        0.000
 35     3194.540        3194.540         yes       1.00000    4.567        4.567        0.000        4.567        0.000
 36     3754.280        3754.280         yes       1.00000    5.367        5.367        0.000        5.367        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  25.45373       The ln(Q)    3.23686
    H vibration       67.42157   (kcal/mol)    282.09186     (kJ/mol)         0.10744302    (hartree)
    U vibration       67.42157   (kcal/mol)    282.09186     (kJ/mol)         0.10744302    (hartree)
           ZPE        64.78865   (kcal/mol)    271.07571     (kJ/mol)         0.10324719    (hartree)
    S vibration       15.26439  (cal/mol*K)     63.86621    (J/mol*K)         0.00002433  (hartree/K)
   Cv vibration       20.41442  (cal/mol*K)     85.41394    (J/mol*K)         0.00003253  (hartree/K)
    G vibration       62.87049   (kcal/mol)    263.05014     (kJ/mol)         0.10019042    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total     548370171481601.12500       The ln(Q)   38.83244
        H total       69.79151   (kcal/mol)    292.00770     (kJ/mol)         0.11121976    (hartree)
        U total       69.19903   (kcal/mol)    289.52874     (kJ/mol)         0.11027557    (hartree)
       Cv total       26.37604  (cal/mol*K)    110.35736    (J/mol*K)         0.00004203  (hartree/K)
           ZPE        64.78865   (kcal/mol)    271.07571     (kJ/mol)         0.10324719    (hartree)
        S total       84.22266  (cal/mol*K)    352.38763    (J/mol*K)         0.00013422  (hartree/K)
        G total       45.27301   (kcal/mol)    189.42228     (kJ/mol)         0.07214707    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.11027557 (hartree)
                       Thermal correction to Enthalpy :   0.11121976 
              Thermal correction to Gibbs Free Energy :   0.07120289 (hartree)
              ZPE correction to the Electronic Energy :   0.10324719 (hartree)


