       
       Thermochemistry v.1.0.0 (28.05.2024)
       Copyright: Yury Minenkov
       N.N. Semenov Federal Research Center
       of Chemical Physics RAS
       119991 Moscow, The Russian Federation
       Kosygina street, 4
       
The thermochemical analysis of the Molecule:                 O2N1C6H5

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  O     8   15.99491      -2.4822430000      -1.2413800000       0.1483840000
  O     8   15.99491      -2.5992260000       0.9657960000      -0.1761310000
  N     7   14.00307       1.6006770000      -1.2513070000       0.2044590000
  C     6   12.00000      -0.4580680000      -0.0486990000       0.0009990000
  C     6   12.00000       0.2305610000       1.1465190000      -0.1646160000
  C     6   12.00000       0.2749750000      -1.2184720000       0.1819220000
  C     6   12.00000       1.6106300000       1.1209910000      -0.1424070000
  C     6   12.00000       2.2447780000      -0.1002280000       0.0447050000
  C     6   12.00000      -1.9365470000      -0.0266130000      -0.0220330000
  H     1    1.00782      -0.3286840000       2.0635190000      -0.3062200000
  H     1    1.00782      -0.2379600000      -2.1650270000       0.3135160000
  H     1    1.00782       2.1919780000       2.0259620000      -0.2669880000
  H     1    1.00782       3.3296750000      -0.1545920000       0.0671620000
  H     1    1.00782      -3.4405460000      -1.1164700000       0.1172490000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.98300
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.27424568     -0.08769754      0.00915382

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       126.50966        -4.79579        -4.68137
    y        -4.79579       404.71744        18.04715
    z        -4.68137        18.04715       525.82160

              Principal moments of inertia (amu*A**2): 
             126.37907000         528.52435000         402.14528000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              395917.39413       The ln(Q)   12.88896

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       28.59384  (cal/mol*K)    119.63662    (J/mol*K)         0.00004557  (hartree/K)
  G rotation       -7.63652   (kcal/mol)    -31.95122     (kJ/mol)        -0.01216957    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   123.03203   amu

              *****      Translation thermodynamic functions     ******

  Q translation            53639227.92083       The ln(Q)   17.79779
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       40.33590  (cal/mol*K)    168.76543    (J/mol*K)         0.00006428  (hartree/K)
  G translation      -10.54494   (kcal/mol)    -44.12001     (kJ/mol)        -0.01680441    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                            The approximation : msRRHO of Grimme
                        TAU= 25.0 ALPHA=  4.0 ENTHALPY_CORRECTION=    1
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       64.170          63.079         yes       3.81049    0.090        0.590        4.333       -0.702        1.948
  2      159.000         156.297         yes       1.88811    0.223        0.620        2.594       -0.153        1.895
  3      210.190         206.617         yes       1.58469    0.295        0.641        2.073        0.023        1.830
  4      388.640         382.033         yes       1.18800    0.546        0.751        1.031        0.444        1.508
  5      389.390         382.770         yes       1.18721    0.547        0.752        1.028        0.446        1.507
  6      430.090         422.778         yes       1.14943    0.604        0.785        0.883        0.522        1.421
  7      497.670         489.210         yes       1.10418    0.699        0.845        0.686        0.641        1.274
  8      599.480         589.289         yes       1.06181    0.842        0.947        0.468        0.807        1.055
  9      625.180         614.552         yes       1.05433    0.879        0.974        0.425        0.847        1.001
 10      661.900         650.648         yes       1.04525    0.930        1.014        0.370        0.904        0.927
 11      727.840         715.467         yes       1.03270    1.023        1.090        0.288        1.004        0.800
 12      769.430         756.350         yes       1.02669    1.081        1.139        0.246        1.066        0.725
 13      800.310         786.705         yes       1.02297    1.125        1.176        0.218        1.111        0.673
 14      859.250         844.643         yes       1.01727    1.207        1.249        0.174        1.197        0.580
 15      973.420         956.872         yes       1.00998    1.368        1.395        0.111        1.362        0.427
 16     1009.310         992.152         yes       1.00840    1.418        1.442        0.097        1.413        0.386
 17     1025.860        1008.420         yes       1.00776    1.442        1.464        0.090        1.437        0.368
 18     1046.290        1028.503         yes       1.00704    1.470        1.491        0.083        1.466        0.347
 19     1073.790        1055.536         yes       1.00617    1.509        1.528        0.075        1.505        0.320
 20     1134.920        1115.626         yes       1.00461    1.595        1.610        0.058        1.592        0.267
 21     1143.330        1123.893         yes       1.00443    1.607        1.621        0.057        1.604        0.260
 22     1214.100        1193.460         yes       1.00316    1.706        1.717        0.042        1.704        0.209
 23     1234.610        1213.622         yes       1.00287    1.735        1.745        0.039        1.733        0.196
 24     1330.220        1307.606         yes       1.00182    1.869        1.876        0.026        1.868        0.144
 25     1359.480        1336.369         yes       1.00158    1.910        1.916        0.023        1.909        0.131
 26     1402.450        1378.608         yes       1.00129    1.971        1.976        0.020        1.970        0.114
 27     1466.010        1441.088         yes       1.00096    2.060        2.064        0.015        2.060        0.092
 28     1525.430        1499.498         yes       1.00072    2.144        2.147        0.012        2.143        0.075
 29     1641.290        1613.388         yes       1.00042    2.306        2.308        0.007        2.306        0.050
 30     1664.440        1636.145         yes       1.00037    2.339        2.341        0.007        2.339        0.046
 31     1828.060        1796.983         yes       1.00017    2.569        2.570        0.003        2.569        0.026
 32     3172.710        3118.774         yes       1.00000    4.459        4.459        0.000        4.459        0.000
 33     3200.940        3146.524         yes       1.00000    4.498        4.498        0.000        4.498        0.000
 34     3211.190        3156.600         yes       1.00000    4.513        4.513        0.000        4.513        0.000
 35     3224.870        3170.047         yes       1.00000    4.532        4.532        0.000        4.532        0.000
 36     3794.170        3729.669         yes       1.00000    5.332        5.332        0.000        5.332        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  28.02249       The ln(Q)    3.33301
    H vibration       67.11680   (kcal/mol)    280.81671     (kJ/mol)         0.10695734    (hartree)
    U vibration       67.11680   (kcal/mol)    280.81671     (kJ/mol)         0.10695734    (hartree)
           ZPE        64.44484   (kcal/mol)    269.63720     (kJ/mol)         0.10269929    (hartree)
    S vibration       15.58532  (cal/mol*K)     65.20899    (J/mol*K)         0.00002484  (hartree/K)
   Cv vibration       20.60335  (cal/mol*K)     86.20440    (J/mol*K)         0.00003283  (hartree/K)
    G vibration       62.47004   (kcal/mol)    261.37464     (kJ/mol)         0.09955225    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total     595105249964267.50000       The ln(Q)   38.92859
        H total       69.48675   (kcal/mol)    290.73255     (kJ/mol)         0.11073408    (hartree)
        U total       68.89426   (kcal/mol)    288.25359     (kJ/mol)         0.10978989    (hartree)
       Cv total       26.56497  (cal/mol*K)    111.14782    (J/mol*K)         0.00004233  (hartree/K)
           ZPE        64.44484   (kcal/mol)    269.63720     (kJ/mol)         0.10269929    (hartree)
        S total       84.51507  (cal/mol*K)    353.61104    (J/mol*K)         0.00013468  (hartree/K)
        G total       44.88106   (kcal/mol)    187.78237     (kJ/mol)         0.07152246    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.10978989 (hartree)
                       Thermal correction to Enthalpy :   0.11073408 
              Thermal correction to Gibbs Free Energy :   0.07057828 (hartree)
              ZPE correction to the Electronic Energy :   0.10269929 (hartree)


