       
       Thermochemistry v.1.0.0 (28.05.2024)
       Copyright: Yury Minenkov
       N.N. Semenov Federal Research Center
       of Chemical Physics RAS
       119991 Moscow, The Russian Federation
       Kosygina street, 4
       
The thermochemical analysis of the Molecule:                 O2N1C6H5

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  O     8   15.99491      -2.3138620000      -1.1897620000       0.1143670000
  O     8   15.99491      -2.4309160000       1.0349230000      -0.2142700000
  N     7   14.00307       1.7831770000      -1.1938360000       0.1710960000
  C     6   12.00000      -0.2840610000       0.0115320000      -0.0343700000
  C     6   12.00000       0.4092170000       1.2066710000      -0.2001960000
  C     6   12.00000       0.4524530000      -1.1589350000       0.1475750000
  C     6   12.00000       1.7893490000       1.1819930000      -0.1774710000
  C     6   12.00000       2.4277210000      -0.0367310000       0.0102250000
  C     6   12.00000      -1.7615280000       0.0361120000      -0.0583100000
  H     1    1.00782      -0.1437290000       2.1240850000      -0.3424820000
  H     1    1.00782      -0.0541230000      -2.1052190000       0.2794530000
  H     1    1.00782       2.3663590000       2.0875290000      -0.3023790000
  H     1    1.00782       3.5101880000      -0.0899310000       0.0330280000
  H     1    1.00782      -3.2735030000      -1.0539880000       0.0812520000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97000
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.09835272     -0.02711732     -0.02605604

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       127.30574        -4.73987        -4.87265
    y        -4.73987       406.93673        18.22505
    z        -4.87265        18.22505       528.75599

              Principal moments of inertia (amu*A**2): 
             127.17342000         531.49922000         404.32581000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              399354.18384       The ln(Q)   12.89760

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       28.61101  (cal/mol*K)    119.70848    (J/mol*K)         0.00004559  (hartree/K)
  G rotation       -7.64165   (kcal/mol)    -31.97264     (kJ/mol)        -0.01217773    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   123.03203   amu

              *****      Translation thermodynamic functions     ******

  Q translation            53639227.92083       The ln(Q)   17.79779
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       40.33590  (cal/mol*K)    168.76543    (J/mol*K)         0.00006428  (hartree/K)
  G translation      -10.54494   (kcal/mol)    -44.12001     (kJ/mol)        -0.01680441    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                            The approximation : msRRHO of Grimme
                        TAU= 25.0 ALPHA=  4.0 ENTHALPY_CORRECTION=    1
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       56.320          54.630         yes       4.31516    0.078        0.583        4.592       -0.786        1.934
  2      149.990         145.490         yes       1.98235    0.208        0.616        2.730       -0.198        1.907
  3      214.570         208.133         yes       1.57796    0.298        0.641        2.060        0.027        1.828
  4      363.510         352.605         yes       1.22309    0.504        0.729        1.155        0.385        1.570
  5      383.520         372.014         yes       1.19917    0.532        0.744        1.071        0.424        1.530
  6      414.330         401.900         yes       1.16793    0.575        0.768        0.956        0.483        1.466
  7      489.350         474.670         yes       1.11260    0.679        0.831        0.725        0.615        1.306
  8      594.780         576.937         yes       1.06585    0.825        0.933        0.491        0.787        1.081
  9      623.180         604.485         yes       1.05719    0.864        0.963        0.442        0.831        1.022
 10      652.840         633.255         yes       1.04941    0.905        0.995        0.396        0.877        0.962
 11      699.610         678.622         yes       1.03931    0.970        1.046        0.332        0.947        0.871
 12      740.980         718.751         yes       1.03217    1.028        1.094        0.285        1.009        0.794
 13      783.980         760.461         yes       1.02615    1.087        1.144        0.242        1.072        0.718
 14      824.720         799.978         yes       1.02151    1.144        1.193        0.207        1.131        0.651
 15      930.810         902.886         yes       1.01298    1.291        1.324        0.138        1.283        0.496
 16      963.440         934.537         yes       1.01112    1.336        1.366        0.122        1.329        0.455
 17      977.990         948.650         yes       1.01038    1.356        1.384        0.115        1.350        0.437
 18     1034.170        1003.145         yes       1.00796    1.434        1.457        0.092        1.429        0.374
 19     1048.750        1017.288         yes       1.00743    1.454        1.476        0.087        1.450        0.359
 20     1102.130        1069.066         yes       1.00578    1.528        1.546        0.071        1.525        0.308
 21     1127.080        1093.268         yes       1.00514    1.563        1.579        0.064        1.560        0.286
 22     1201.910        1165.853         yes       1.00362    1.667        1.679        0.048        1.665        0.228
 23     1222.740        1186.058         yes       1.00328    1.696        1.707        0.044        1.694        0.214
 24     1307.620        1268.391         yes       1.00220    1.813        1.821        0.031        1.812        0.164
 25     1358.830        1318.065         yes       1.00173    1.884        1.891        0.025        1.883        0.139
 26     1372.200        1331.034         yes       1.00163    1.903        1.909        0.024        1.902        0.134
 27     1440.890        1397.663         yes       1.00118    1.998        2.003        0.018        1.997        0.107
 28     1503.380        1458.279         yes       1.00088    2.085        2.088        0.014        2.084        0.087
 29     1593.390        1545.588         yes       1.00058    2.210        2.212        0.010        2.209        0.064
 30     1618.850        1570.284         yes       1.00051    2.245        2.247        0.009        2.245        0.058
 31     1760.520        1707.704         yes       1.00026    2.441        2.443        0.005        2.441        0.036
 32     3110.850        3017.524         yes       1.00000    4.314        4.314        0.000        4.314        0.000
 33     3144.880        3050.534         yes       1.00000    4.361        4.361        0.000        4.361        0.000
 34     3148.130        3053.686         yes       1.00000    4.365        4.365        0.000        4.365        0.000
 35     3163.980        3069.061         yes       1.00000    4.387        4.387        0.000        4.387        0.000
 36     3686.700        3576.099         yes       1.00000    5.112        5.112        0.000        5.112        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  36.92155       The ln(Q)    3.60880
    H vibration       64.95190   (kcal/mol)    271.75876     (kJ/mol)         0.10350735    (hartree)
    U vibration       64.95190   (kcal/mol)    271.75876     (kJ/mol)         0.10350735    (hartree)
           ZPE        62.13861   (kcal/mol)    259.98796     (kJ/mol)         0.09902409    (hartree)
    S vibration       16.60077  (cal/mol*K)     69.45761    (J/mol*K)         0.00002645  (hartree/K)
   Cv vibration       21.58492  (cal/mol*K)     90.31132    (J/mol*K)         0.00003440  (hartree/K)
    G vibration       60.00238   (kcal/mol)    251.04997     (kJ/mol)         0.09561980    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total     790898322263735.62500       The ln(Q)   39.20438
        H total       67.32184   (kcal/mol)    281.67460     (kJ/mol)         0.10728409    (hartree)
        U total       66.72936   (kcal/mol)    279.19564     (kJ/mol)         0.10633991    (hartree)
       Cv total       27.54654  (cal/mol*K)    115.25473    (J/mol*K)         0.00004390  (hartree/K)
           ZPE        62.13861   (kcal/mol)    259.98796     (kJ/mol)         0.09902409    (hartree)
        S total       85.54768  (cal/mol*K)    357.93151    (J/mol*K)         0.00013633  (hartree/K)
        G total       42.40829   (kcal/mol)    177.43628     (kJ/mol)         0.06758185    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.10633991 (hartree)
                       Thermal correction to Enthalpy :   0.10728409 
              Thermal correction to Gibbs Free Energy :   0.06663766 (hartree)
              ZPE correction to the Electronic Energy :   0.09902409 (hartree)


