       
       Thermochemistry v.1.0.0 (28.05.2024)
       Copyright: Yury Minenkov
       N.N. Semenov Federal Research Center
       of Chemical Physics RAS
       119991 Moscow, The Russian Federation
       Kosygina street, 4
       
The thermochemical analysis of the Molecule:                 O2N1C6H5

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  O     8   15.99491      -2.3148130000      -1.1899350000       0.1134880000
  O     8   15.99491      -2.4322160000       1.0385240000      -0.2134230000
  N     7   14.00307       1.7838630000      -1.1968930000       0.1710440000
  C     6   12.00000      -0.2843890000       0.0125320000      -0.0343960000
  C     6   12.00000       0.4087380000       1.2122280000      -0.2006510000
  C     6   12.00000       0.4500610000      -1.1637840000       0.1479390000
  C     6   12.00000       1.7933080000       1.1856220000      -0.1777880000
  C     6   12.00000       2.4320090000      -0.0383240000       0.0102790000
  C     6   12.00000      -1.7660390000       0.0390310000      -0.0584480000
  H     1    1.00782      -0.1493570000       2.1327030000      -0.3431580000
  H     1    1.00782      -0.0625090000      -2.1140870000       0.2801330000
  H     1    1.00782       2.3741270000       2.0941100000      -0.3029580000
  H     1    1.00782       3.5201430000      -0.0919770000       0.0330860000
  H     1    1.00782      -3.2761780000      -1.0653210000       0.0823600000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     1.00000
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.09850644     -0.02642745     -0.02611180

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       128.06640        -4.63797        -4.85649
    y        -4.63797       407.84644        18.27375
    z        -4.85649        18.27375       530.43267

              Principal moments of inertia (amu*A**2): 
             127.93787000         533.17275000         405.23489000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              401633.53885       The ln(Q)   12.90330

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       28.62232  (cal/mol*K)    119.75580    (J/mol*K)         0.00004561  (hartree/K)
  G rotation       -7.64502   (kcal/mol)    -31.98675     (kJ/mol)        -0.01218310    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   123.03203   amu

              *****      Translation thermodynamic functions     ******

  Q translation            53639227.92083       The ln(Q)   17.79779
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       40.33590  (cal/mol*K)    168.76543    (J/mol*K)         0.00006428  (hartree/K)
  G translation      -10.54494   (kcal/mol)    -44.12001     (kJ/mol)        -0.01680441    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                            The approximation : msRRHO of Grimme
                        TAU= 25.0 ALPHA=  4.0 ENTHALPY_CORRECTION=    1
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       66.190          66.190         yes       3.65733    0.095        0.592        4.244       -0.674        1.951
  2      156.450         156.450         yes       1.88687    0.224        0.620        2.592       -0.153        1.895
  3      219.730         219.730         yes       1.52984    0.314        0.647        1.961        0.062        1.811
  4      379.200         379.200         yes       1.19109    0.542        0.749        1.042        0.438        1.514
  5      388.780         388.780         yes       1.18089    0.556        0.757        1.005        0.457        1.494
  6      422.750         422.750         yes       1.14945    0.604        0.785        0.883        0.522        1.421
  7      496.620         496.620         yes       1.10015    0.710        0.852        0.667        0.653        1.258
  8      602.080         602.080         yes       1.05789    0.861        0.960        0.446        0.827        1.027
  9      628.870         628.870         yes       1.05052    0.899        0.990        0.403        0.870        0.971
 10      661.710         661.710         yes       1.04280    0.946        1.027        0.355        0.921        0.904
 11      722.440         722.440         yes       1.03158    1.033        1.098        0.281        1.014        0.787
 12      751.570         751.570         yes       1.02733    1.074        1.133        0.251        1.058        0.734
 13      793.770         793.770         yes       1.02218    1.135        1.185        0.212        1.122        0.661
 14      847.040         847.040         yes       1.01707    1.211        1.252        0.172        1.201        0.576
 15      954.630         954.630         yes       1.01009    1.365        1.392        0.112        1.359        0.430
 16      992.040         992.040         yes       1.00841    1.418        1.442        0.097        1.413        0.386
 17     1010.600        1010.600         yes       1.00768    1.445        1.467        0.090        1.440        0.366
 18     1045.880        1045.880         yes       1.00647    1.495        1.515        0.078        1.491        0.330
 19     1058.980        1058.980         yes       1.00607    1.514        1.532        0.074        1.510        0.317
 20     1111.090        1111.090         yes       1.00471    1.588        1.603        0.060        1.586        0.271
 21     1133.170        1133.170         yes       1.00424    1.620        1.634        0.054        1.617        0.253
 22     1208.210        1208.210         yes       1.00295    1.727        1.737        0.040        1.725        0.200
 23     1229.040        1229.040         yes       1.00266    1.757        1.766        0.037        1.755        0.187
 24     1305.420        1305.420         yes       1.00184    1.866        1.873        0.027        1.865        0.145
 25     1358.230        1358.230         yes       1.00143    1.942        1.947        0.021        1.941        0.122
 26     1375.960        1375.960         yes       1.00131    1.967        1.972        0.020        1.966        0.115
 27     1449.220        1449.220         yes       1.00092    2.072        2.076        0.015        2.071        0.089
 28     1506.750        1506.750         yes       1.00070    2.154        2.157        0.011        2.154        0.073
 29     1603.890        1603.890         yes       1.00044    2.293        2.295        0.008        2.293        0.052
 30     1624.750        1624.750         yes       1.00039    2.323        2.325        0.007        2.322        0.048
 31     1783.160        1783.160         yes       1.00018    2.549        2.550        0.003        2.549        0.027
 32     3137.440        3137.440         yes       1.00000    4.485        4.485        0.000        4.485        0.000
 33     3165.610        3165.610         yes       1.00000    4.525        4.525        0.000        4.525        0.000
 34     3180.900        3180.900         yes       1.00000    4.547        4.547        0.000        4.547        0.000
 35     3194.530        3194.530         yes       1.00000    4.567        4.567        0.000        4.567        0.000
 36     3754.020        3754.020         yes       1.00000    5.367        5.367        0.000        5.367        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  25.46623       The ln(Q)    3.23735
    H vibration       67.42220   (kcal/mol)    282.09449     (kJ/mol)         0.10744402    (hartree)
    U vibration       67.42220   (kcal/mol)    282.09449     (kJ/mol)         0.10744402    (hartree)
           ZPE        64.78922   (kcal/mol)    271.07810     (kJ/mol)         0.10324810    (hartree)
    S vibration       15.26555  (cal/mol*K)     63.87106    (J/mol*K)         0.00002433  (hartree/K)
   Cv vibration       20.41421  (cal/mol*K)     85.41304    (J/mol*K)         0.00003253  (hartree/K)
    G vibration       62.87078   (kcal/mol)    263.05133     (kJ/mol)         0.10019087    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total     548627065470583.87500       The ln(Q)   38.83294
        H total       69.79214   (kcal/mol)    292.01033     (kJ/mol)         0.11122076    (hartree)
        U total       69.19966   (kcal/mol)    289.53137     (kJ/mol)         0.11027657    (hartree)
       Cv total       26.37583  (cal/mol*K)    110.35646    (J/mol*K)         0.00004203  (hartree/K)
           ZPE        64.78922   (kcal/mol)    271.07810     (kJ/mol)         0.10324810    (hartree)
        S total       84.22378  (cal/mol*K)    352.39228    (J/mol*K)         0.00013422  (hartree/K)
        G total       45.27331   (kcal/mol)    189.42353     (kJ/mol)         0.07214755    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.11027657 (hartree)
                       Thermal correction to Enthalpy :   0.11122076 
              Thermal correction to Gibbs Free Energy :   0.07120336 (hartree)
              ZPE correction to the Electronic Energy :   0.10324810 (hartree)


