       
       Thermochemistry v.1.0.0 (28.05.2024)
       Copyright: Yury Minenkov
       N.N. Semenov Federal Research Center
       of Chemical Physics RAS
       119991 Moscow, The Russian Federation
       Kosygina street, 4
       
The thermochemical analysis of the Molecule:                 O2N1C6H5

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  O     8   15.99491      -2.3139660000      -1.1897570000       0.1140160000
  O     8   15.99491      -2.4308050000       1.0350300000      -0.2137300000
  N     7   14.00307       1.7832940000      -1.1940400000       0.1705110000
  C     6   12.00000      -0.2840240000       0.0114640000      -0.0341810000
  C     6   12.00000       0.4092150000       1.2066870000      -0.1997080000
  C     6   12.00000       0.4525430000      -1.1589760000       0.1472130000
  C     6   12.00000       1.7893540000       1.1819830000      -0.1772290000
  C     6   12.00000       2.4277340000      -0.0367590000       0.0099120000
  C     6   12.00000      -1.7615780000       0.0361630000      -0.0579340000
  H     1    1.00782      -0.1438540000       2.1240900000      -0.3415750000
  H     1    1.00782      -0.0539480000      -2.1053490000       0.2788440000
  H     1    1.00782       2.3661820000       2.0876580000      -0.3019390000
  H     1    1.00782       3.5101980000      -0.0900010000       0.0325010000
  H     1    1.00782      -3.2735980000      -1.0537630000       0.0808060000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97000
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.09833116     -0.02713248     -0.02603950

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       127.30341        -4.72734        -4.83881
    y        -4.72734       406.93140        18.18011
    z        -4.83881        18.18011       528.77717

              Principal moments of inertia (amu*A**2): 
             127.17224000         531.50599000         404.33375000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              399358.80598       The ln(Q)   12.89762

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       28.61104  (cal/mol*K)    119.70858    (J/mol*K)         0.00004559  (hartree/K)
  G rotation       -7.64165   (kcal/mol)    -31.97267     (kJ/mol)        -0.01217774    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   123.03203   amu

              *****      Translation thermodynamic functions     ******

  Q translation            53639227.92083       The ln(Q)   17.79779
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       40.33590  (cal/mol*K)    168.76543    (J/mol*K)         0.00006428  (hartree/K)
  G translation      -10.54494   (kcal/mol)    -44.12001     (kJ/mol)        -0.01680441    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                            The approximation : msRRHO of Grimme
                        TAU= 25.0 ALPHA=  4.0 ENTHALPY_CORRECTION=    1
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       56.230          54.543         yes       4.32120    0.078        0.583        4.595       -0.787        1.934
  2      149.950         145.451         yes       1.98272    0.208        0.616        2.731       -0.198        1.907
  3      214.520         208.084         yes       1.57818    0.297        0.641        2.060        0.027        1.828
  4      363.410         352.508         yes       1.22322    0.504        0.729        1.155        0.385        1.570
  5      383.470         371.966         yes       1.19923    0.532        0.744        1.072        0.424        1.530
  6      414.380         401.949         yes       1.16788    0.575        0.768        0.956        0.483        1.466
  7      489.350         474.670         yes       1.11260    0.679        0.831        0.725        0.615        1.306
  8      595.360         577.499         yes       1.06566    0.826        0.934        0.490        0.788        1.080
  9      622.990         604.300         yes       1.05724    0.864        0.963        0.442        0.831        1.023
 10      652.650         633.070         yes       1.04945    0.905        0.995        0.396        0.876        0.963
 11      699.550         678.563         yes       1.03932    0.970        1.046        0.333        0.947        0.871
 12      741.010         718.780         yes       1.03216    1.028        1.094        0.285        1.009        0.794
 13      783.980         760.461         yes       1.02615    1.087        1.144        0.242        1.072        0.718
 14      824.730         799.988         yes       1.02151    1.144        1.193        0.207        1.131        0.651
 15      930.830         902.905         yes       1.01298    1.291        1.324        0.138        1.283        0.496
 16      963.480         934.576         yes       1.01112    1.336        1.366        0.122        1.329        0.455
 17      977.960         948.621         yes       1.01038    1.356        1.384        0.115        1.350        0.437
 18     1033.880        1002.864         yes       1.00797    1.434        1.457        0.092        1.429        0.374
 19     1048.800        1017.336         yes       1.00743    1.454        1.476        0.087        1.450        0.359
 20     1102.200        1069.134         yes       1.00578    1.528        1.546        0.071        1.525        0.307
 21     1127.120        1093.306         yes       1.00514    1.563        1.579        0.064        1.560        0.286
 22     1201.920        1165.862         yes       1.00362    1.667        1.679        0.048        1.665        0.228
 23     1222.740        1186.058         yes       1.00328    1.696        1.707        0.044        1.694        0.214
 24     1307.560        1268.333         yes       1.00220    1.813        1.821        0.031        1.812        0.164
 25     1358.870        1318.104         yes       1.00173    1.884        1.891        0.025        1.883        0.139
 26     1372.210        1331.044         yes       1.00163    1.903        1.909        0.024        1.902        0.134
 27     1441.000        1397.770         yes       1.00118    1.998        2.003        0.018        1.998        0.107
 28     1503.330        1458.230         yes       1.00088    2.085        2.088        0.014        2.084        0.087
 29     1593.450        1545.647         yes       1.00058    2.210        2.212        0.010        2.209        0.064
 30     1618.810        1570.246         yes       1.00051    2.245        2.247        0.009        2.244        0.058
 31     1760.830        1708.005         yes       1.00026    2.442        2.443        0.005        2.442        0.036
 32     3110.900        3017.573         yes       1.00000    4.314        4.314        0.000        4.314        0.000
 33     3144.760        3050.417         yes       1.00000    4.361        4.361        0.000        4.361        0.000
 34     3148.150        3053.706         yes       1.00000    4.365        4.365        0.000        4.365        0.000
 35     3164.000        3069.080         yes       1.00000    4.387        4.387        0.000        4.387        0.000
 36     3686.380        3575.789         yes       1.00000    5.112        5.112        0.000        5.112        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  36.98638       The ln(Q)    3.61055
    H vibration       64.95180   (kcal/mol)    271.75834     (kJ/mol)         0.10350719    (hartree)
    U vibration       64.95180   (kcal/mol)    271.75834     (kJ/mol)         0.10350719    (hartree)
           ZPE        62.13839   (kcal/mol)    259.98703     (kJ/mol)         0.09902374    (hartree)
    S vibration       16.60455  (cal/mol*K)     69.47342    (J/mol*K)         0.00002646  (hartree/K)
   Cv vibration       21.58466  (cal/mol*K)     90.31024    (J/mol*K)         0.00003440  (hartree/K)
    G vibration       60.00116   (kcal/mol)    251.04484     (kJ/mol)         0.09561784    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total     792296219021842.25000       The ln(Q)   39.20613
        H total       67.32174   (kcal/mol)    281.67418     (kJ/mol)         0.10728393    (hartree)
        U total       66.72926   (kcal/mol)    279.19522     (kJ/mol)         0.10633975    (hartree)
       Cv total       27.54628  (cal/mol*K)    115.25365    (J/mol*K)         0.00004390  (hartree/K)
           ZPE        62.13839   (kcal/mol)    259.98703     (kJ/mol)         0.09902374    (hartree)
        S total       85.55149  (cal/mol*K)    357.94742    (J/mol*K)         0.00013633  (hartree/K)
        G total       42.40705   (kcal/mol)    177.43111     (kJ/mol)         0.06757988    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.10633975 (hartree)
                       Thermal correction to Enthalpy :   0.10728393 
              Thermal correction to Gibbs Free Energy :   0.06663570 (hartree)
              ZPE correction to the Electronic Energy :   0.09902374 (hartree)


