       
       Thermochemistry v.1.0.0 (28.05.2024)
       Copyright: Yury Minenkov
       N.N. Semenov Federal Research Center
       of Chemical Physics RAS
       119991 Moscow, The Russian Federation
       Kosygina street, 4
       
The thermochemical analysis of the Molecule:                 O2N1C6H5

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  O     8   15.99491      -2.3054400000      -1.1805610000       0.1124600000
  O     8   15.99491      -2.4222970000       1.0266130000      -0.2123370000
  N     7   14.00307       1.7776390000      -1.1902610000       0.1699270000
  C     6   12.00000      -0.2810690000       0.0123320000      -0.0339980000
  C     6   12.00000       0.4075680000       1.2075580000      -0.1997580000
  C     6   12.00000       0.4519610000      -1.1573520000       0.1471980000
  C     6   12.00000       1.7876720000       1.1820420000      -0.1773570000
  C     6   12.00000       2.4216840000      -0.0391650000       0.0100470000
  C     6   12.00000      -1.7597080000       0.0343720000      -0.0571440000
  H     1    1.00782      -0.1517890000       2.1244330000      -0.3415640000
  H     1    1.00782      -0.0609870000      -2.1038750000       0.2789240000
  H     1    1.00782       2.3686940000       2.0871610000      -0.3020380000
  H     1    1.00782       3.5065420000      -0.0936350000       0.0326720000
  H     1    1.00782      -3.2637220000      -1.0552310000       0.0804770000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.98300
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.09731234     -0.02670766     -0.02603928

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       126.51512        -4.81737        -4.79284
    y        -4.81737       404.74367        18.06279
    z        -4.79284        18.06279       525.83783

              Principal moments of inertia (amu*A**2): 
             126.38135000         528.54830000         402.16697000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              395940.62390       The ln(Q)   12.88902

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       28.59395  (cal/mol*K)    119.63711    (J/mol*K)         0.00004557  (hartree/K)
  G rotation       -7.63656   (kcal/mol)    -31.95136     (kJ/mol)        -0.01216962    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   123.03203   amu

              *****      Translation thermodynamic functions     ******

  Q translation            53639227.92083       The ln(Q)   17.79779
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       40.33590  (cal/mol*K)    168.76543    (J/mol*K)         0.00006428  (hartree/K)
  G translation      -10.54494   (kcal/mol)    -44.12001     (kJ/mol)        -0.01680441    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                            The approximation : msRRHO of Grimme
                        TAU= 25.0 ALPHA=  4.0 ENTHALPY_CORRECTION=    1
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       64.300          63.207         yes       3.80390    0.090        0.590        4.330       -0.701        1.949
  2      158.920         156.218         yes       1.88874    0.223        0.620        2.595       -0.154        1.895
  3      210.280         206.705         yes       1.58429    0.295        0.641        2.073        0.023        1.830
  4      388.590         381.984         yes       1.18806    0.546        0.751        1.031        0.444        1.509
  5      389.280         382.662         yes       1.18733    0.547        0.752        1.029        0.445        1.507
  6      430.040         422.729         yes       1.14947    0.604        0.785        0.883        0.522        1.421
  7      497.620         489.160         yes       1.10420    0.699        0.845        0.686        0.641        1.274
  8      599.940         589.741         yes       1.06166    0.843        0.947        0.468        0.808        1.054
  9      625.180         614.552         yes       1.05433    0.879        0.974        0.425        0.847        1.001
 10      661.940         650.687         yes       1.04524    0.930        1.014        0.370        0.904        0.927
 11      727.690         715.319         yes       1.03272    1.023        1.090        0.288        1.004        0.800
 12      769.430         756.350         yes       1.02669    1.081        1.139        0.246        1.066        0.725
 13      800.240         786.636         yes       1.02298    1.125        1.176        0.218        1.111        0.673
 14      859.160         844.554         yes       1.01728    1.207        1.249        0.174        1.197        0.580
 15      973.420         956.872         yes       1.00998    1.368        1.395        0.111        1.362        0.427
 16     1009.250         992.093         yes       1.00840    1.418        1.442        0.097        1.413        0.386
 17     1025.660        1008.224         yes       1.00777    1.441        1.464        0.090        1.437        0.368
 18     1046.270        1028.483         yes       1.00704    1.470        1.491        0.083        1.466        0.347
 19     1073.780        1055.526         yes       1.00617    1.509        1.528        0.075        1.505        0.320
 20     1134.840        1115.548         yes       1.00461    1.595        1.609        0.059        1.592        0.267
 21     1143.210        1123.775         yes       1.00443    1.607        1.621        0.057        1.604        0.260
 22     1214.250        1193.608         yes       1.00316    1.706        1.717        0.042        1.704        0.209
 23     1234.660        1213.671         yes       1.00287    1.735        1.745        0.039        1.733        0.196
 24     1330.230        1307.616         yes       1.00182    1.869        1.876        0.026        1.868        0.144
 25     1359.480        1336.369         yes       1.00158    1.910        1.916        0.023        1.909        0.131
 26     1402.410        1378.569         yes       1.00129    1.971        1.976        0.020        1.970        0.114
 27     1466.050        1441.127         yes       1.00096    2.060        2.064        0.015        2.060        0.092
 28     1525.320        1499.390         yes       1.00072    2.143        2.147        0.012        2.143        0.075
 29     1641.330        1613.427         yes       1.00042    2.307        2.308        0.007        2.306        0.050
 30     1664.360        1636.066         yes       1.00037    2.339        2.341        0.007        2.339        0.046
 31     1828.290        1797.209         yes       1.00017    2.569        2.570        0.003        2.569        0.026
 32     3172.950        3119.010         yes       1.00000    4.459        4.459        0.000        4.459        0.000
 33     3200.970        3146.554         yes       1.00000    4.498        4.498        0.000        4.498        0.000
 34     3211.470        3156.875         yes       1.00000    4.513        4.513        0.000        4.513        0.000
 35     3225.140        3170.313         yes       1.00000    4.532        4.532        0.000        4.532        0.000
 36     3793.370        3728.883         yes       1.00000    5.331        5.331        0.000        5.331        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  27.97954       The ln(Q)    3.33147
    H vibration       67.11661   (kcal/mol)    280.81590     (kJ/mol)         0.10695703    (hartree)
    U vibration       67.11661   (kcal/mol)    280.81590     (kJ/mol)         0.10695703    (hartree)
           ZPE        64.44468   (kcal/mol)    269.63655     (kJ/mol)         0.10269905    (hartree)
    S vibration       15.58220  (cal/mol*K)     65.19593    (J/mol*K)         0.00002483  (hartree/K)
   Cv vibration       20.60381  (cal/mol*K)     86.20635    (J/mol*K)         0.00003283  (hartree/K)
    G vibration       62.47078   (kcal/mol)    261.37773     (kJ/mol)         0.09955343    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total     594228065475693.87500       The ln(Q)   38.92706
        H total       69.48655   (kcal/mol)    290.73174     (kJ/mol)         0.11073377    (hartree)
        U total       68.89407   (kcal/mol)    288.25278     (kJ/mol)         0.10978958    (hartree)
       Cv total       26.56543  (cal/mol*K)    111.14976    (J/mol*K)         0.00004233  (hartree/K)
           ZPE        64.44468   (kcal/mol)    269.63655     (kJ/mol)         0.10269905    (hartree)
        S total       84.51206  (cal/mol*K)    353.59846    (J/mol*K)         0.00013468  (hartree/K)
        G total       44.88177   (kcal/mol)    187.78531     (kJ/mol)         0.07152358    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.10978958 (hartree)
                       Thermal correction to Enthalpy :   0.11073377 
              Thermal correction to Gibbs Free Energy :   0.07057940 (hartree)
              ZPE correction to the Electronic Energy :   0.10269905 (hartree)


