       
       Thermochemistry v.1.0.0 (28.05.2024)
       Copyright: Yury Minenkov
       N.N. Semenov Federal Research Center
       of Chemical Physics RAS
       119991 Moscow, The Russian Federation
       Kosygina street, 4
       
The thermochemical analysis of the Molecule:                 O2N1C6H5

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  O     8   15.99491      -2.4907960000      -1.2506860000       0.1497670000
  O     8   15.99491      -2.6077720000       0.9741530000      -0.1776050000
  N     7   14.00307       1.6063220000      -1.2550470000       0.2050380000
  C     6   12.00000      -0.4609800000      -0.0495350000       0.0010460000
  C     6   12.00000       0.2322300000       1.1457370000      -0.1644820000
  C     6   12.00000       0.2755880000      -1.2200820000       0.1820990000
  C     6   12.00000       1.6123520000       1.1209580000      -0.1423530000
  C     6   12.00000       2.2508120000      -0.0978620000       0.0444590000
  C     6   12.00000      -1.9384060000      -0.0248060000      -0.0223340000
  H     1    1.00782      -0.3208310000       2.0631760000      -0.3060760000
  H     1    1.00782      -0.2309420000      -2.1664310000       0.3137080000
  H     1    1.00782       2.1895700000       2.0264060000      -0.2670380000
  H     1    1.00782       3.3333020000      -0.1509810000       0.0667500000
  H     1    1.00782      -3.4504500000      -1.1150020000       0.1170240000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97000
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.27526177     -0.08812671      0.00919185

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       127.30103        -4.71292        -4.72276
    y        -4.71292       406.91046        18.16415
    z        -4.72276        18.16415       528.76983

              Principal moments of inertia (amu*A**2): 
             127.17291000         531.49066000         404.31775000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              399346.19452       The ln(Q)   12.89758

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       28.61097  (cal/mol*K)    119.70832    (J/mol*K)         0.00004559  (hartree/K)
  G rotation       -7.64163   (kcal/mol)    -31.97259     (kJ/mol)        -0.01217771    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   123.03203   amu

              *****      Translation thermodynamic functions     ******

  Q translation            53639227.92083       The ln(Q)   17.79779
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       40.33590  (cal/mol*K)    168.76543    (J/mol*K)         0.00006428  (hartree/K)
  G translation      -10.54494   (kcal/mol)    -44.12001     (kJ/mol)        -0.01680441    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                            The approximation : msRRHO of Grimme
                        TAU= 25.0 ALPHA=  4.0 ENTHALPY_CORRECTION=    1
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       56.330          54.640         yes       4.31449    0.078        0.583        4.592       -0.786        1.934
  2      150.050         145.549         yes       1.98181    0.208        0.616        2.729       -0.197        1.907
  3      214.570         208.133         yes       1.57796    0.298        0.641        2.060        0.027        1.828
  4      363.600         352.692         yes       1.22298    0.504        0.729        1.154        0.385        1.570
  5      383.530         372.024         yes       1.19916    0.532        0.744        1.071        0.424        1.530
  6      414.370         401.939         yes       1.16789    0.575        0.768        0.956        0.483        1.466
  7      489.360         474.679         yes       1.11260    0.679        0.831        0.725        0.615        1.306
  8      594.910         577.063         yes       1.06581    0.825        0.934        0.491        0.787        1.081
  9      623.170         604.475         yes       1.05719    0.864        0.963        0.442        0.831        1.022
 10      652.830         633.245         yes       1.04941    0.905        0.995        0.396        0.877        0.962
 11      699.680         678.690         yes       1.03930    0.970        1.046        0.332        0.947        0.871
 12      740.990         718.760         yes       1.03217    1.028        1.094        0.285        1.009        0.794
 13      784.000         760.480         yes       1.02615    1.087        1.144        0.242        1.072        0.718
 14      824.780         800.037         yes       1.02151    1.144        1.193        0.207        1.131        0.651
 15      930.840         902.915         yes       1.01298    1.291        1.324        0.138        1.283        0.496
 16      963.460         934.556         yes       1.01112    1.336        1.366        0.122        1.329        0.455
 17      977.960         948.621         yes       1.01038    1.356        1.384        0.115        1.350        0.437
 18     1034.190        1003.164         yes       1.00796    1.434        1.457        0.092        1.429        0.374
 19     1048.750        1017.288         yes       1.00743    1.454        1.476        0.087        1.450        0.359
 20     1102.210        1069.144         yes       1.00578    1.528        1.546        0.071        1.525        0.307
 21     1127.020        1093.209         yes       1.00514    1.563        1.579        0.064        1.560        0.286
 22     1201.910        1165.853         yes       1.00362    1.667        1.679        0.048        1.665        0.228
 23     1222.710        1186.029         yes       1.00328    1.696        1.707        0.044        1.694        0.214
 24     1307.610        1268.382         yes       1.00220    1.813        1.821        0.031        1.812        0.164
 25     1358.820        1318.055         yes       1.00173    1.884        1.891        0.025        1.883        0.139
 26     1372.150        1330.986         yes       1.00163    1.903        1.909        0.024        1.902        0.134
 27     1440.860        1397.634         yes       1.00118    1.998        2.003        0.018        1.997        0.107
 28     1503.410        1458.308         yes       1.00088    2.085        2.088        0.014        2.084        0.087
 29     1593.360        1545.559         yes       1.00058    2.209        2.212        0.010        2.209        0.064
 30     1618.860        1570.294         yes       1.00051    2.245        2.247        0.009        2.245        0.058
 31     1760.410        1707.598         yes       1.00026    2.441        2.442        0.005        2.441        0.036
 32     3110.770        3017.447         yes       1.00000    4.314        4.314        0.000        4.314        0.000
 33     3144.840        3050.495         yes       1.00000    4.361        4.361        0.000        4.361        0.000
 34     3148.060        3053.618         yes       1.00000    4.365        4.365        0.000        4.365        0.000
 35     3164.060        3069.138         yes       1.00000    4.388        4.388        0.000        4.388        0.000
 36     3686.850        3576.244         yes       1.00000    5.112        5.112        0.000        5.112        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  36.89827       The ln(Q)    3.60816
    H vibration       64.95216   (kcal/mol)    271.75984     (kJ/mol)         0.10350776    (hartree)
    U vibration       64.95216   (kcal/mol)    271.75984     (kJ/mol)         0.10350776    (hartree)
           ZPE        62.13911   (kcal/mol)    259.99004     (kJ/mol)         0.09902489    (hartree)
    S vibration       16.59872  (cal/mol*K)     69.44904    (J/mol*K)         0.00002645  (hartree/K)
   Cv vibration       21.58407  (cal/mol*K)     90.30775    (J/mol*K)         0.00003440  (hartree/K)
    G vibration       60.00325   (kcal/mol)    251.05361     (kJ/mol)         0.09562118    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total     790383980034712.87500       The ln(Q)   39.20375
        H total       67.32210   (kcal/mol)    281.67568     (kJ/mol)         0.10728450    (hartree)
        U total       66.72962   (kcal/mol)    279.19672     (kJ/mol)         0.10634032    (hartree)
       Cv total       27.54569  (cal/mol*K)    115.25116    (J/mol*K)         0.00004390  (hartree/K)
           ZPE        62.13911   (kcal/mol)    259.99004     (kJ/mol)         0.09902489    (hartree)
        S total       85.54560  (cal/mol*K)    357.92278    (J/mol*K)         0.00013633  (hartree/K)
        G total       42.40917   (kcal/mol)    177.43996     (kJ/mol)         0.06758325    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.10634032 (hartree)
                       Thermal correction to Enthalpy :   0.10728450 
              Thermal correction to Gibbs Free Energy :   0.06663907 (hartree)
              ZPE correction to the Electronic Energy :   0.09902489 (hartree)


