       
       Thermochemistry v.1.0.0 (28.05.2024)
       Copyright: Yury Minenkov
       N.N. Semenov Federal Research Center
       of Chemical Physics RAS
       119991 Moscow, The Russian Federation
       Kosygina street, 4
       
The thermochemical analysis of the Molecule:                 O2N1C6H5

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  O     8   15.99491      -2.2349340000      -1.1363170000      -0.0000990000
  O     8   15.99491      -2.3142300000       1.1140800000       0.0002110000
  N     7   14.00307       1.8616670000      -1.2173830000      -0.0003650000
  C     6   12.00000      -0.1849680000       0.0395730000      -0.0000460000
  C     6   12.00000       0.5285520000       1.2342970000       0.0001220000
  C     6   12.00000       0.5316470000      -1.1570710000      -0.0002900000
  C     6   12.00000       1.9081680000       1.1834320000       0.0000510000
  C     6   12.00000       2.5257990000      -0.0601570000      -0.0001930000
  C     6   12.00000      -1.6618690000       0.0921580000       0.0000470000
  H     1    1.00782      -0.0087310000       2.1718360000       0.0003120000
  H     1    1.00782       0.0090610000      -2.1038500000      -0.0004270000
  H     1    1.00782       2.5004630000       2.0877180000       0.0001830000
  H     1    1.00782       3.6072870000      -0.1342900000      -0.0002580000
  H     1    1.00782      -3.1922060000      -0.9811880000      -0.0000340000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97000
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00009924     -0.00298811     -0.00005896

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       127.17074         0.66680         0.02075
    y         0.66680       404.32002        -0.02053
    z         0.02075        -0.02053       531.49076

              Principal moments of inertia (amu*A**2): 
             127.16914000         404.32162000         531.49076000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              399342.21833       The ln(Q)   12.89757

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       28.61095  (cal/mol*K)    119.70823    (J/mol*K)         0.00004559  (hartree/K)
  G rotation       -7.64163   (kcal/mol)    -31.97257     (kJ/mol)        -0.01217770    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   123.03203   amu

              *****      Translation thermodynamic functions     ******

  Q translation            53639227.92083       The ln(Q)   17.79779
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       40.33590  (cal/mol*K)    168.76543    (J/mol*K)         0.00006428  (hartree/K)
  G translation      -10.54494   (kcal/mol)    -44.12001     (kJ/mol)        -0.01680441    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                            The approximation : msRRHO of Grimme
                        TAU= 25.0 ALPHA=  4.0 ENTHALPY_CORRECTION=    1
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       56.130          54.446         yes       4.32793    0.078        0.583        4.598       -0.788        1.934
  2      149.950         145.451         yes       1.98272    0.208        0.616        2.731       -0.198        1.907
  3      214.230         207.803         yes       1.57942    0.297        0.641        2.063        0.026        1.829
  4      363.430         352.527         yes       1.22319    0.504        0.729        1.155        0.385        1.570
  5      383.500         371.995         yes       1.19919    0.532        0.744        1.072        0.424        1.530
  6      414.180         401.755         yes       1.16807    0.574        0.767        0.956        0.482        1.466
  7      489.320         474.640         yes       1.11262    0.679        0.831        0.725        0.615        1.306
  8      594.910         577.063         yes       1.06581    0.825        0.934        0.491        0.787        1.081
  9      623.160         604.465         yes       1.05719    0.864        0.963        0.442        0.831        1.022
 10      652.860         633.274         yes       1.04940    0.905        0.995        0.396        0.877        0.962
 11      699.540         678.554         yes       1.03932    0.970        1.046        0.333        0.947        0.871
 12      740.970         718.741         yes       1.03217    1.027        1.094        0.285        1.009        0.794
 13      784.010         760.490         yes       1.02615    1.087        1.144        0.242        1.072        0.718
 14      824.680         799.940         yes       1.02152    1.144        1.193        0.207        1.131        0.651
 15      930.860         902.934         yes       1.01298    1.291        1.324        0.138        1.283        0.496
 16      963.500         934.595         yes       1.01112    1.336        1.366        0.122        1.330        0.454
 17      978.000         948.660         yes       1.01038    1.356        1.384        0.115        1.350        0.437
 18     1034.090        1003.067         yes       1.00797    1.434        1.457        0.092        1.429        0.374
 19     1048.780        1017.317         yes       1.00743    1.454        1.476        0.087        1.450        0.359
 20     1102.160        1069.095         yes       1.00578    1.528        1.546        0.071        1.525        0.307
 21     1127.000        1093.190         yes       1.00514    1.563        1.579        0.064        1.560        0.286
 22     1201.900        1165.843         yes       1.00362    1.667        1.679        0.048        1.665        0.228
 23     1222.660        1185.980         yes       1.00328    1.695        1.707        0.044        1.694        0.214
 24     1307.450        1268.226         yes       1.00220    1.813        1.821        0.031        1.812        0.164
 25     1358.660        1317.900         yes       1.00173    1.884        1.891        0.025        1.883        0.140
 26     1372.160        1330.995         yes       1.00163    1.903        1.909        0.024        1.902        0.134
 27     1440.860        1397.634         yes       1.00118    1.998        2.003        0.018        1.997        0.107
 28     1503.260        1458.162         yes       1.00088    2.085        2.088        0.014        2.084        0.087
 29     1593.320        1545.520         yes       1.00058    2.209        2.212        0.010        2.209        0.064
 30     1618.710        1570.149         yes       1.00051    2.245        2.247        0.009        2.244        0.058
 31     1760.800        1707.976         yes       1.00026    2.442        2.443        0.005        2.442        0.036
 32     3110.730        3017.408         yes       1.00000    4.314        4.314        0.000        4.314        0.000
 33     3144.770        3050.427         yes       1.00000    4.361        4.361        0.000        4.361        0.000
 34     3148.070        3053.628         yes       1.00000    4.365        4.365        0.000        4.365        0.000
 35     3163.920        3069.002         yes       1.00000    4.387        4.387        0.000        4.387        0.000
 36     3686.690        3576.089         yes       1.00000    5.112        5.112        0.000        5.112        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  37.07963       The ln(Q)    3.61307
    H vibration       64.95014   (kcal/mol)    271.75138     (kJ/mol)         0.10350454    (hartree)
    U vibration       64.95014   (kcal/mol)    271.75138     (kJ/mol)         0.10350454    (hartree)
           ZPE        62.13626   (kcal/mol)    259.97809     (kJ/mol)         0.09902034    (hartree)
    S vibration       16.61101  (cal/mol*K)     69.50045    (J/mol*K)         0.00002647  (hartree/K)
   Cv vibration       21.58569  (cal/mol*K)     90.31451    (J/mol*K)         0.00003440  (hartree/K)
    G vibration       59.99757   (kcal/mol)    251.02982     (kJ/mol)         0.09561212    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total     794260868461320.62500       The ln(Q)   39.20865
        H total       67.32008   (kcal/mol)    281.66722     (kJ/mol)         0.10728128    (hartree)
        U total       66.72760   (kcal/mol)    279.18826     (kJ/mol)         0.10633710    (hartree)
       Cv total       27.54731  (cal/mol*K)    115.25793    (J/mol*K)         0.00004390  (hartree/K)
           ZPE        62.13626   (kcal/mol)    259.97809     (kJ/mol)         0.09902034    (hartree)
        S total       85.55787  (cal/mol*K)    357.97411    (J/mol*K)         0.00013635  (hartree/K)
        G total       42.40349   (kcal/mol)    177.41620     (kJ/mol)         0.06757420    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.10633710 (hartree)
                       Thermal correction to Enthalpy :   0.10728128 
              Thermal correction to Gibbs Free Energy :   0.06663002 (hartree)
              ZPE correction to the Electronic Energy :   0.09902034 (hartree)


