       
       Thermochemistry v.1.0.0 (28.05.2024)
       Copyright: Yury Minenkov
       N.N. Semenov Federal Research Center
       of Chemical Physics RAS
       119991 Moscow, The Russian Federation
       Kosygina street, 4
       
The thermochemical analysis of the Molecule:                 O2N1C6H5

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  O     8   15.99491      -2.2262350000      -1.1268880000      -0.0001490000
  O     8   15.99491      -2.3056950000       1.1057990000       0.0002590000
  N     7   14.00307       1.8561810000      -1.2136060000      -0.0003600000
  C     6   12.00000      -0.1820900000       0.0402930000      -0.0000300000
  C     6   12.00000       0.5268830000       1.2349450000       0.0001210000
  C     6   12.00000       0.5311260000      -1.1554020000      -0.0002870000
  C     6   12.00000       1.9064620000       1.1834620000       0.0000400000
  C     6   12.00000       2.5197430000      -0.0624290000      -0.0001880000
  C     6   12.00000      -1.6602550000       0.0904220000       0.0001010000
  H     1    1.00782      -0.0163250000       2.1723020000       0.0003030000
  H     1    1.00782       0.0022330000      -2.1023370000      -0.0004000000
  H     1    1.00782       2.5024750000       2.0874550000       0.0001490000
  H     1    1.00782       3.6036170000      -0.1379360000      -0.0002560000
  H     1    1.00782      -3.1824150000      -0.9832420000      -0.0000890000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.98300
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00113131     -0.00253340     -0.00005277

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       126.38067         0.58003         0.02165
    y         0.58003       402.15396        -0.02189
    z         0.02165        -0.02189       528.53462

              Principal moments of inertia (amu*A**2): 
             126.37945000         402.15517000         528.53462000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              395926.71279       The ln(Q)   12.88898

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       28.59388  (cal/mol*K)    119.63681    (J/mol*K)         0.00004557  (hartree/K)
  G rotation       -7.63654   (kcal/mol)    -31.95128     (kJ/mol)        -0.01216959    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   123.03203   amu

              *****      Translation thermodynamic functions     ******

  Q translation            53639227.92083       The ln(Q)   17.79779
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       40.33590  (cal/mol*K)    168.76543    (J/mol*K)         0.00006428  (hartree/K)
  G translation      -10.54494   (kcal/mol)    -44.12001     (kJ/mol)        -0.01680441    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                            The approximation : msRRHO of Grimme
                        TAU= 25.0 ALPHA=  4.0 ENTHALPY_CORRECTION=    1
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       64.040          62.951         yes       3.81710    0.090        0.590        4.337       -0.703        1.948
  2      158.830         156.130         yes       1.88946    0.223        0.620        2.596       -0.154        1.895
  3      210.220         206.646         yes       1.58456    0.295        0.641        2.073        0.023        1.830
  4      388.590         381.984         yes       1.18806    0.546        0.751        1.031        0.444        1.509
  5      389.320         382.702         yes       1.18728    0.547        0.752        1.028        0.445        1.507
  6      429.990         422.680         yes       1.14951    0.604        0.785        0.883        0.522        1.421
  7      497.700         489.239         yes       1.10416    0.699        0.845        0.686        0.641        1.274
  8      599.310         589.122         yes       1.06186    0.842        0.946        0.469        0.807        1.055
  9      625.270         614.640         yes       1.05430    0.879        0.974        0.425        0.847        1.001
 10      661.870         650.618         yes       1.04526    0.930        1.014        0.370        0.904        0.927
 11      727.750         715.378         yes       1.03271    1.023        1.090        0.288        1.004        0.800
 12      769.340         756.261         yes       1.02670    1.081        1.139        0.246        1.066        0.726
 13      800.480         786.872         yes       1.02295    1.125        1.177        0.218        1.111        0.673
 14      859.200         844.594         yes       1.01727    1.207        1.249        0.174        1.197        0.580
 15      973.490         956.941         yes       1.00997    1.368        1.395        0.111        1.362        0.427
 16     1009.370         992.211         yes       1.00840    1.418        1.442        0.097        1.413        0.386
 17     1025.830        1008.391         yes       1.00776    1.442        1.464        0.090        1.437        0.368
 18     1046.410        1028.621         yes       1.00704    1.470        1.491        0.083        1.466        0.347
 19     1073.900        1055.644         yes       1.00617    1.509        1.528        0.075        1.505        0.320
 20     1135.020        1115.725         yes       1.00461    1.595        1.610        0.058        1.592        0.267
 21     1143.560        1124.119         yes       1.00443    1.607        1.621        0.056        1.604        0.260
 22     1213.950        1193.313         yes       1.00317    1.706        1.717        0.043        1.704        0.209
 23     1234.620        1213.631         yes       1.00287    1.735        1.745        0.039        1.733        0.196
 24     1330.300        1307.685         yes       1.00182    1.869        1.876        0.026        1.868        0.144
 25     1359.550        1336.438         yes       1.00158    1.911        1.917        0.023        1.910        0.131
 26     1402.420        1378.579         yes       1.00129    1.971        1.976        0.020        1.970        0.114
 27     1466.070        1441.147         yes       1.00096    2.060        2.064        0.015        2.060        0.092
 28     1525.390        1499.458         yes       1.00072    2.144        2.147        0.012        2.143        0.075
 29     1641.510        1613.604         yes       1.00042    2.307        2.309        0.007        2.307        0.050
 30     1664.460        1636.164         yes       1.00037    2.339        2.341        0.007        2.339        0.046
 31     1828.450        1797.366         yes       1.00017    2.569        2.570        0.003        2.569        0.026
 32     3172.600        3118.666         yes       1.00000    4.458        4.458        0.000        4.458        0.000
 33     3200.760        3146.347         yes       1.00000    4.498        4.498        0.000        4.498        0.000
 34     3211.180        3156.590         yes       1.00000    4.513        4.513        0.000        4.513        0.000
 35     3224.850        3170.028         yes       1.00000    4.532        4.532        0.000        4.532        0.000
 36     3794.180        3729.679         yes       1.00000    5.332        5.332        0.000        5.332        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  28.09423       The ln(Q)    3.33556
    H vibration       67.11768   (kcal/mol)    280.82037     (kJ/mol)         0.10695873    (hartree)
    U vibration       67.11768   (kcal/mol)    280.82037     (kJ/mol)         0.10695873    (hartree)
           ZPE        64.44533   (kcal/mol)    269.63926     (kJ/mol)         0.10270008    (hartree)
    S vibration       15.59164  (cal/mol*K)     65.23540    (J/mol*K)         0.00002485  (hartree/K)
   Cv vibration       20.60346  (cal/mol*K)     86.20486    (J/mol*K)         0.00003283  (hartree/K)
    G vibration       62.46903   (kcal/mol)    261.37043     (kJ/mol)         0.09955065    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total     596642895158344.62500       The ln(Q)   38.93115
        H total       69.48762   (kcal/mol)    290.73621     (kJ/mol)         0.11073547    (hartree)
        U total       68.89514   (kcal/mol)    288.25725     (kJ/mol)         0.10979129    (hartree)
       Cv total       26.56508  (cal/mol*K)    111.14828    (J/mol*K)         0.00004233  (hartree/K)
           ZPE        64.44533   (kcal/mol)    269.63926     (kJ/mol)         0.10270008    (hartree)
        S total       84.52143  (cal/mol*K)    353.63764    (J/mol*K)         0.00013469  (hartree/K)
        G total       44.88004   (kcal/mol)    187.77810     (kJ/mol)         0.07152084    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.10979129 (hartree)
                       Thermal correction to Enthalpy :   0.11073547 
              Thermal correction to Gibbs Free Energy :   0.07057665 (hartree)
              ZPE correction to the Electronic Energy :   0.10270008 (hartree)


