       
       Thermochemistry v.1.0.0 (28.05.2024)
       Copyright: Yury Minenkov
       N.N. Semenov Federal Research Center
       of Chemical Physics RAS
       119991 Moscow, The Russian Federation
       Kosygina street, 4
       
The thermochemical analysis of the Molecule:                 O2N1C6H5

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  O     8   15.99491      -2.2358630000      -1.1364030000      -0.0001130000
  O     8   15.99491      -2.3154690000       1.1175050000       0.0002150000
  N     7   14.00307       1.8623170000      -1.2204060000      -0.0003620000
  C     6   12.00000      -0.1852520000       0.0405740000      -0.0000420000
  C     6   12.00000       0.5281570000       1.2398610000       0.0001240000
  C     6   12.00000       0.5291930000      -1.1618840000      -0.0002730000
  C     6   12.00000       1.9121580000       1.1870190000       0.0000480000
  C     6   12.00000       2.5300290000      -0.0617910000      -0.0002060000
  C     6   12.00000      -1.6662980000       0.0951050000       0.0000610000
  H     1    1.00782      -0.0141890000       2.1805630000       0.0003180000
  H     1    1.00782       0.0004250000      -2.1125290000      -0.0004220000
  H     1    1.00782       2.5083620000       2.0941550000       0.0001810000
  H     1    1.00782       3.6171730000      -0.1363910000      -0.0002640000
  H     1    1.00782      -3.1950390000      -0.9925390000      -0.0000510000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     1.00000
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.00003742     -0.00230635     -0.00005798

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       127.93634         0.76320         0.02093
    y         0.76320       405.22368        -0.02067
    z         0.02093        -0.02067       533.16002

              Principal moments of inertia (amu*A**2): 
             127.93424000         405.22578000         533.16002000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              401618.52623       The ln(Q)   12.90326

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       28.62225  (cal/mol*K)    119.75549    (J/mol*K)         0.00004561  (hartree/K)
  G rotation       -7.64500   (kcal/mol)    -31.98666     (kJ/mol)        -0.01218306    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   123.03203   amu

              *****      Translation thermodynamic functions     ******

  Q translation            53639227.92083       The ln(Q)   17.79779
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       40.33590  (cal/mol*K)    168.76543    (J/mol*K)         0.00006428  (hartree/K)
  G translation      -10.54494   (kcal/mol)    -44.12001     (kJ/mol)        -0.01680441    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                            The approximation : msRRHO of Grimme
                        TAU= 25.0 ALPHA=  4.0 ENTHALPY_CORRECTION=    1
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       65.780          65.780         yes       3.67668    0.094        0.591        4.255       -0.677        1.951
  2      156.450         156.450         yes       1.88687    0.224        0.620        2.592       -0.153        1.895
  3      219.760         219.760         yes       1.52972    0.314        0.647        1.961        0.062        1.811
  4      379.240         379.240         yes       1.19104    0.542        0.749        1.042        0.439        1.514
  5      388.770         388.770         yes       1.18090    0.556        0.757        1.005        0.457        1.494
  6      422.490         422.490         yes       1.14967    0.604        0.785        0.884        0.521        1.421
  7      496.600         496.600         yes       1.10016    0.710        0.852        0.667        0.653        1.258
  8      602.230         602.230         yes       1.05785    0.861        0.961        0.446        0.828        1.027
  9      628.830         628.830         yes       1.05053    0.899        0.990        0.403        0.870        0.971
 10      661.760         661.760         yes       1.04279    0.946        1.027        0.355        0.921        0.904
 11      722.390         722.390         yes       1.03159    1.033        1.098        0.281        1.014        0.787
 12      751.460         751.460         yes       1.02734    1.074        1.133        0.251        1.058        0.734
 13      793.790         793.790         yes       1.02218    1.135        1.185        0.212        1.122        0.661
 14      846.920         846.920         yes       1.01708    1.211        1.252        0.172        1.201        0.577
 15      954.510         954.510         yes       1.01009    1.365        1.392        0.112        1.359        0.430
 16      991.940         991.940         yes       1.00841    1.418        1.442        0.097        1.413        0.386
 17     1010.540        1010.540         yes       1.00768    1.445        1.467        0.090        1.440        0.366
 18     1045.850        1045.850         yes       1.00647    1.495        1.514        0.078        1.491        0.330
 19     1058.970        1058.970         yes       1.00607    1.514        1.532        0.074        1.510        0.317
 20     1111.170        1111.170         yes       1.00471    1.588        1.603        0.060        1.586        0.271
 21     1132.940        1132.940         yes       1.00424    1.620        1.633        0.054        1.617        0.253
 22     1208.300        1208.300         yes       1.00294    1.727        1.738        0.040        1.726        0.200
 23     1229.170        1229.170         yes       1.00266    1.757        1.767        0.037        1.756        0.187
 24     1305.390        1305.390         yes       1.00184    1.866        1.873        0.027        1.865        0.145
 25     1358.300        1358.300         yes       1.00143    1.942        1.947        0.021        1.941        0.122
 26     1376.090        1376.090         yes       1.00131    1.967        1.972        0.020        1.966        0.115
 27     1449.210        1449.210         yes       1.00092    2.072        2.076        0.015        2.071        0.089
 28     1506.820        1506.820         yes       1.00070    2.154        2.157        0.011        2.154        0.073
 29     1603.920        1603.920         yes       1.00044    2.293        2.295        0.008        2.293        0.052
 30     1624.700        1624.700         yes       1.00039    2.323        2.324        0.007        2.322        0.048
 31     1783.630        1783.630         yes       1.00018    2.550        2.551        0.003        2.550        0.027
 32     3137.360        3137.360         yes       1.00000    4.485        4.485        0.000        4.485        0.000
 33     3165.370        3165.370         yes       1.00000    4.525        4.525        0.000        4.525        0.000
 34     3180.860        3180.860         yes       1.00000    4.547        4.547        0.000        4.547        0.000
 35     3194.440        3194.440         yes       1.00000    4.567        4.567        0.000        4.567        0.000
 36     3753.960        3753.960         yes       1.00000    5.367        5.367        0.000        5.367        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  25.60331       The ln(Q)    3.24272
    H vibration       67.42155   (kcal/mol)    282.09177     (kJ/mol)         0.10744298    (hartree)
    U vibration       67.42155   (kcal/mol)    282.09177     (kJ/mol)         0.10744298    (hartree)
           ZPE        64.78806   (kcal/mol)    271.07326     (kJ/mol)         0.10324626    (hartree)
    S vibration       15.27780  (cal/mol*K)     63.92231    (J/mol*K)         0.00002435  (hartree/K)
   Cv vibration       20.41475  (cal/mol*K)     85.41532    (J/mol*K)         0.00003253  (hartree/K)
    G vibration       62.86647   (kcal/mol)    263.03333     (kJ/mol)         0.10018401    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total     551559543034735.31250       The ln(Q)   38.83830
        H total       69.79149   (kcal/mol)    292.00761     (kJ/mol)         0.11121972    (hartree)
        U total       69.19901   (kcal/mol)    289.52865     (kJ/mol)         0.11027554    (hartree)
       Cv total       26.37637  (cal/mol*K)    110.35873    (J/mol*K)         0.00004203  (hartree/K)
           ZPE        64.78806   (kcal/mol)    271.07326     (kJ/mol)         0.10324626    (hartree)
        S total       84.23595  (cal/mol*K)    352.44323    (J/mol*K)         0.00013424  (hartree/K)
        G total       45.26903   (kcal/mol)    189.40562     (kJ/mol)         0.07214073    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.11027554 (hartree)
                       Thermal correction to Enthalpy :   0.11121972 
              Thermal correction to Gibbs Free Energy :   0.07119654 (hartree)
              ZPE correction to the Electronic Energy :   0.10324626 (hartree)


